### ISSUE TITLE
005 Video Group Test fails on OS X 10.10 (Yosemite)

### ISSUE THREAD

**Issue by andrewvy** [phpsdl/extension#18]
Uploading make test output to a gist..

https://gist.github.com/andrewvy/db0100b536f0f325e0e9 Let me know if this helps.

This might be why running the `draw-pixels.php` example doesn't work for me..

```
php draw-pixels.php                                                                                                                                                                                       
PHP Warning:  Module 'SDL' already loaded in Unknown on line 0

Warning: Module 'SDL' already loaded in Unknown on line 0
PHP Fatal error:  Call to undefined function SDL_SetVideoMode() in /Users/andrewvy/Sites/examples/draw-pixels.php on line 12

Fatal error: Call to undefined function SDL_SetVideoMode() in /Users/andrewvy/Sites/examples/draw-pixels.php on line 12
```

EDIT: Just kidding, it looks like some examples in this repo work. But all examples in https://github.com/phpsdl/examples do not work. This may be my fault, I might have to compile from source for SDL 1.2 devel libs.

**Comment by santiagolizardo** [comment]
Thanks for reporting this @andrewvy . (Un)fortunately I'm unable to reproduce this issue with make test on Yosemite.
The reason why phpsdl/examples is not working is because all those examples are meant to be used with SDL1.2 and the extension is now working with SDL2. I'll update the examples accordingly to not cause more confusion.
Thanks 

![image](https://cloud.githubusercontent.com/assets/220190/7844349/a856498e-04a7-11e5-831f-2b523b0a3efb.png)

**Comment by andrewvy** [comment]
@santiagolizardo Can you post your output for `php examples/version.php` so I can make sure I have the correct versions installed?
